export { default as Header } from './header'
export { default as Intro } from './intro'
export { default as Project } from './project'
export { default as About } from './about'
export { default as Footer } from './footer'